config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/about'

  devise_for :users
  resources :users, only: [:show]
  resources :wikis
  resources :charges, only: [:new, :create]
  resources :wikis do
   resources :charges, only: [:new, :create]
   resources :collaborates, only: [:create, :destroy]
  end
  root to: 'wikis#index'


end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborates, dependent: :destroy
  has_many :users, through: :collaborates

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 10 }, presence: true
  validates :user, presence: true

  scope :visible_to, -> (user) { user.role == 'admin' || user.role == 'premium' ? all : where(private: false) }

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
   before_action :authenticate_user!, except: [:show, :new, :create]

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wikis = Wiki.all
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
    @user = current_user
  end

  def create
   @wiki = Wiki.new
   @wiki.title = params[:wiki][:title]
   @wiki.body = params[:wiki][:body]
   @wiki.user = current_user
   @wiki.private = params[:wiki][:private]

   if @wiki.save
     flash[:notice] = "Wiki was saved."
     redirect_to @wiki
   else
     flash.now[:alert] = "There was a problem saving the wiki."
     render :new
   end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = User.all
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private
  def wiki_params
    params.require(:wiki).permit(:title, :body)
  end

end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.erb
  <%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  </div>

  <% if current_user.admin? || current_user.premium? %>
  <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
          Private  <%= f.check_box :private, class: "private-checkbox"  %>
        <% end %>
  </div>
  <% end %>
  <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
  <% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
<div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
</div>

<div class="col-md-8">
  <%= render partial: 'collaborators/users' %>
  <%= render partial: 'collaborators/form', locals: { wiki: @wiki} %>
</div>

app/views/wikis/index.html.erb
<div class="row">
  <div class="col-md-8">
  <h1>Wiki Topics</h1>
  <h4><em>Click to start contributing now!</em></h4>
    <% @wikis.each do |wiki| %>
    <% if (current_user.admin? || current_user.premium? || wiki.users.include?(current_user)) || !(wiki.private?) %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to wiki.title, edit_wiki_path(wiki) %>
            <%= link_to "Edit", edit_wiki_path(wiki), class: 'btn btn-success' %>
            <%= link_to "Delete", wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
          </h4>
        </div>
      </div>
    <% end %>
    <% end %>
    <div class="row">
      <div class="col-md-8">
       <%= link_to "New wiki", new_wiki_path(@wiki), class: 'btn btn-success' %>
      </div>
    </div>
  </div>

app/views/wikis/new.html.erb
<div class="col-md-8">
   <%= render partial: 'form', locals: { wiki: @wiki } %>
</div>

app/views/wikis/show.html.erb
<div class="jumbotron">
<div class="row">
  <div class="col-md-8">
  <% @wikis.each do |wiki| %>
  <% if (current_user.admin? || current_user.premium? || wiki.users.include?(current_user)) || !(wiki.private?) %>
     <h3><%= markdown(wiki.title)%></h3>
     <p><%= markdown(wiki.body) %></p>
     <%= link_to "Edit", edit_wiki_path(wiki), class: 'btn btn-success' %>
     <%= link_to "Delete", wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
   <% end %>
   <% end %>
  </div>
</div>
</div>