config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/about'

  devise_for :users
  resources :users, only: [:show]
  resources :wikis
  resources :charges, only: [:new, :create]
  resources :wikis do
   resources :charges, only: [:new, :create]
   resources :collaborates, only: [:create, :destroy]
  end
  root to: 'wikis#index'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>

   <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
      <li><%= link_to "Home", welcome_index_path %></li>
      <li><%= link_to "Subscribe", new_charge_path %></li>
      <li><%= link_to "About",welcome_about_path %></li>
      <li><%= link_to "Wikis",wikis_path %></li>
    </ul>
     <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
     <% if user_signed_in? %>
     Signed in as: <strong><%= current_user.email %></strong> |
     <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
   <% else %>
     <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
     <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
   <% end %>
    <%= yield %>
  </div>
  <script>blocmetrics.report('about page loaded');</script>
  </body>
</html>